site_name: "Mail.tm SDK"
repo_url: https://github.com/halfstackpgr/Mail.tm
theme:
  name: material
  font:
    code: JetBrains Mono
  icon:
    logo: fontawesome/solid/book
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: octicons/moon-24
        name: Switch to light mode
  features:
    - content.tabs.link
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - content.action.view
    - content.action.edit
    - content.tooltips
    - toc.follow
    - announce.dismiss


nav:
  - Home: index.md
  - Client System:
    - Client System: home/client.md
    - Future Plans: home/future.md
  - Server System:
      - Server Introduction: server/server.md
      - Server Implementation: server/implementation.md
      - Server Events: server/events.md
      - Server Limitations: server/limitations.md
      - References: server/references.md
  - Async Client: references/async-client.md
  - Sync Server: references\sync-client.md
  - Pullers: references/pullers.md
  - ABCs and Errors:
    - ABC: references/abc.md
    - Errors: references/errors.md
    - Methods: references/methods.md



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - privacy
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3.10/objects.inv
            - https://docs.hikari-py.dev/en/latest/objects.inv
            - https://tanjun.cursed.solutions/objects.inv
            - https://alluka.cursed.solutions/objects.inv
            - https://arc.hypergonial.com/objects.inv
          options:
            heading_level: 3
            annotations_path: source
            members_order: source
            group_by_category: true
            docstring_section_style: spacy
            docstring_style: numpy
            inherited_members: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_source: false
            show_submodules: false
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            extensions:
                - griffe_inherited_docstrings
            filters:
              - "!^_"
              - "!^__init_subclass__"